server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - AddRequestHeader=first-request, Namgon-first-req
            - AddResponseHeader=first-response, Namgon-first-res

        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-header, Namgon-second
            - AddResponseHeader=second-response, Hello

        # user service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            # 원 주소 -> 바뀔 주소. 패스를 다시 지정한다.
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # catalog service
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            # 원 주소 -> 바뀔 주소. 패스를 다시 지정한다.
            - RewritePath=/catalog-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
